### ISSUE TITLE
AttributeError: 'MediaFileUpload' object has no attribute '_fd'

### ISSUE THREAD

**Issue by Verdatabo** [ClarityCoders/GoogleDrive#1]
I did the code as exactly per the instructions but  it seems like theres error i cant bypass.

```
PS E:\SEMESTER 6\FYP\CODE\Chy_phy_pro_google_Drive> python setup1.py
Traceback (most recent call last):
  File "setup1.py", line 91, in <module>
    main()
  File "setup1.py", line 87, in main
    my_drive.upload_file(item, path)
  File "setup1.py", line 54, in upload_file
    media = MediaFileUpload(f"{path}{filename}")
  File "C:\Users\JYNX\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\googleapiclient\_helpers.py", line 134, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "C:\Users\JYNX\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\googleapiclient\http.py", line 575, in __init__
    fd = open(self._filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'E:\\SEMESTER 6\\FYP\\CODE\\Driveinfra.jpeg'
Exception ignored in: <function MediaFileUpload.__del__ at 0x0000024653121A60>
Traceback (most recent call last):
  File "C:\Users\JYNX\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\googleapiclient\http.py", line 587, in __del__
    self._fd.close()
AttributeError: 'MediaFileUpload' object has no attribute '_fd'
PS E:\SEMESTER 6\FYP\CODE\Chy_phy_pro_google_Drive> 
```

**Comment by Verdatabo** [comment]
```
import pickle
import os.path
from googleapiclient.discovery import build
from google_auth_oauthlib.flow import InstalledAppFlow
from google.auth.transport.requests import Request
from apiclient.http import MediaFileUpload

import os


class MyDrive():
    def __init__(self):
        # If modifying these scopes, delete the file token.pickle.
        SCOPES = ['https://www.googleapis.com/auth/drive']
        """Shows basic usage of the Drive v3 API.
        Prints the names and ids of the first 10 files the user has access to.
        """
        creds = None
        # The file token.pickle stores the user's access and refresh tokens, and is
        # created automatically when the authorization flow completes for the first
        # time.
        if os.path.exists('token.pickle'):
            with open('token.pickle', 'rb') as token:
                creds = pickle.load(token)
        # If there are no (valid) credentials available, let the user log in.
        if not creds or not creds.valid:
            if creds and creds.expired and creds.refresh_token:
                creds.refresh(Request())
            else:
                flow = InstalledAppFlow.from_client_secrets_file(
                    'credentials.json', SCOPES)
                creds = flow.run_local_server(port=0)
            # Save the credentials for the next run
            with open('token.pickle', 'wb') as token:
                pickle.dump(creds, token)

        self.service = build('drive', 'v3', credentials=creds)

    def list_files(self, page_size=10):
        # Call the Drive v3 API
        results = self.service.files().list(
            pageSize=page_size, fields="nextPageToken, files(id, name)").execute()
        items = results.get('files', [])

        if not items:
            print('No files found.')
        else:
            print('Files:')
            for item in items:
                print(u'{0} ({1})'.format(item['name'], item['id']))

    def upload_file(self, filename, path):
        folder_id = "1yyCJ1fV1gtvBILTg-9PLZ1OOTGGFAgfr"
        media = MediaFileUpload(f"{path}{filename}")

        response = self.service.files().list(
                                        q=f"name='{filename}' and parents='{folder_id}'",
                                        spaces='drive',
                                        fields='nextPageToken, files(id, name)',
                                        pageToken=None).execute()
        if len(response['files']) == 0:
            file_metadata = {
                'name': filename,
                'parents': [folder_id]
            }
            file = self.service.files().create(body=file_metadata, media_body=media, fields='id').execute()
            print(f"A new file was created {file.get('id')}")

        else:
            for file in response.get('files', []):
                # Process change

                update_file = self.service.files().update(
                    fileId=file.get('id'),
                    media_body=media,
                ).execute()
                print(f'Updated File')


def main():
    path="E:\SEMESTER 6\FYP\CODE\Drive"   #This can be  used in any pc but the  folder that backs up must apply dir
    files = os.listdir(path)
    my_drive = MyDrive()
    #my_drive.list_files()

    for item in files:
        my_drive.upload_file(item, path)


if __name__ == '__main__':
    main()
```
